version: 0.2
os: linux
phases:
  install:
    commands:
      - wget https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
      - tar -xvf openjdk-13.0.1_linux-x64_bin.tar.gz
      - mv jdk-13.0.1 /opt/
      - JAVA_HOME='/opt/jdk-13.0.1'
      - PATH="$JAVA_HOME/bin:$PATH"
      - export PATH
      - java -version
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      - tar -xvf apache-maven-3.9.9-bin.tar.gz
      - mv apache-maven-3.9.9 /opt/
      - M2_HOME='/opt/apache-maven-3.9.9'
      - PATH="$M2_HOME/bin:$PATH"
      - export PATH
      - mvn -version
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/codeguru-profiler-java-agent-standalone-1.0.0.jar'
